# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: comment_censor.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x63omment_censor.proto\x12\x0e\x63omment_censor\";\n\x14\x43ommentCensorRequest\x12\x12\n\ncomment_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"/\n\x15\x43ommentCensorResponse\x12\x16\n\x0e\x63\x65nsor_content\x18\x01 \x01(\t2s\n\x14\x43ommentCensorService\x12[\n\x0c\x43heckComment\x12$.comment_censor.CommentCensorRequest\x1a%.comment_censor.CommentCensorResponseB\rZ\x0b/comment_pbb\x06proto3')



_COMMENTCENSORREQUEST = DESCRIPTOR.message_types_by_name['CommentCensorRequest']
_COMMENTCENSORRESPONSE = DESCRIPTOR.message_types_by_name['CommentCensorResponse']
CommentCensorRequest = _reflection.GeneratedProtocolMessageType('CommentCensorRequest', (_message.Message,), {
  'DESCRIPTOR' : _COMMENTCENSORREQUEST,
  '__module__' : 'comment_censor_pb2'
  # @@protoc_insertion_point(class_scope:comment_censor.CommentCensorRequest)
  })
_sym_db.RegisterMessage(CommentCensorRequest)

CommentCensorResponse = _reflection.GeneratedProtocolMessageType('CommentCensorResponse', (_message.Message,), {
  'DESCRIPTOR' : _COMMENTCENSORRESPONSE,
  '__module__' : 'comment_censor_pb2'
  # @@protoc_insertion_point(class_scope:comment_censor.CommentCensorResponse)
  })
_sym_db.RegisterMessage(CommentCensorResponse)

_COMMENTCENSORSERVICE = DESCRIPTOR.services_by_name['CommentCensorService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\013/comment_pb'
  _COMMENTCENSORREQUEST._serialized_start=40
  _COMMENTCENSORREQUEST._serialized_end=99
  _COMMENTCENSORRESPONSE._serialized_start=101
  _COMMENTCENSORRESPONSE._serialized_end=148
  _COMMENTCENSORSERVICE._serialized_start=150
  _COMMENTCENSORSERVICE._serialized_end=265
# @@protoc_insertion_point(module_scope)
