# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

# import comment_censor_pb2 as comment__censor__pb2

from grpc_pkg.comment_pb import comment_censor_pb2 as comment__censor__pb2

class CommentCensorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckComment = channel.unary_unary(
                '/comment_censor.CommentCensorService/CheckComment',
                request_serializer=comment__censor__pb2.CommentCensorRequest.SerializeToString,
                response_deserializer=comment__censor__pb2.CommentCensorResponse.FromString,
                )


class CommentCensorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CheckComment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CommentCensorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckComment': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckComment,
                    request_deserializer=comment__censor__pb2.CommentCensorRequest.FromString,
                    response_serializer=comment__censor__pb2.CommentCensorResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'comment_censor.CommentCensorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CommentCensorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CheckComment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/comment_censor.CommentCensorService/CheckComment',
            comment__censor__pb2.CommentCensorRequest.SerializeToString,
            comment__censor__pb2.CommentCensorResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
